import type { WidgetManifest } from "./types";

/**
 * Built-in widget manifest definitions.
 * Each DOFIS page/feature is registered as a native widget.
 */

export const BUILTIN_MANIFESTS: WidgetManifest[] = [
  {
    id: "urule:approval-queue",
    name: "Approval Queue",
    version: "0.1.0",
    description: "View and manage pending approval requests",
    author: "urule",
    mountPoints: ["main-panel", "sidebar"],
    entryType: "native",
    componentPath: "approval-queue",
    permissions: ["read:approvals", "write:approvals"],
    defaultConfig: {},
    icon: "verified_user",
    category: "admin",
  },
  {
    id: "urule:approval-detail",
    name: "Approval Detail",
    version: "0.1.0",
    description: "Detailed view of an individual approval request",
    author: "urule",
    mountPoints: ["main-panel", "drawer"],
    entryType: "native",
    componentPath: "approval-detail",
    permissions: ["read:approvals", "write:approvals"],
    defaultConfig: {},
    icon: "fact_check",
    category: "admin",
  },
  {
    id: "urule:sandbox-monitor",
    name: "Sandbox Monitor",
    version: "0.1.0",
    description: "Monitor running sandbox sessions and resource usage",
    author: "urule",
    mountPoints: ["sidebar", "main-panel"],
    entryType: "native",
    componentPath: "sandbox-monitor",
    permissions: ["read:runtimes"],
    defaultConfig: {},
    icon: "monitor_heart",
    category: "monitoring",
  },
  {
    id: "urule:sandbox-terminal",
    name: "Sandbox Terminal",
    version: "0.1.0",
    description: "Interactive terminal for sandbox sessions",
    author: "urule",
    mountPoints: ["main-panel", "drawer"],
    entryType: "native",
    componentPath: "sandbox-terminal",
    permissions: ["read:runtimes", "write:runtimes"],
    defaultConfig: {},
    icon: "terminal",
    category: "development",
  },
  {
    id: "urule:sandbox-desktop",
    name: "Sandbox Desktop",
    version: "0.1.0",
    description: "Remote desktop view for sandbox sessions",
    author: "urule",
    mountPoints: ["main-panel"],
    entryType: "native",
    componentPath: "sandbox-desktop",
    permissions: ["read:runtimes", "write:runtimes"],
    defaultConfig: {},
    icon: "desktop_windows",
    category: "development",
  },
  {
    id: "urule:dashboard-stats",
    name: "Dashboard Stats",
    version: "0.1.0",
    description: "Overview statistics and agent activity",
    author: "urule",
    mountPoints: ["main-panel", "sidebar"],
    entryType: "native",
    componentPath: "dashboard-stats",
    permissions: ["read:agents", "read:runtimes"],
    defaultConfig: {},
    icon: "dashboard",
    category: "monitoring",
  },
  {
    id: "urule:activity-logs",
    name: "Activity Logs",
    version: "0.1.0",
    description: "System and agent activity log viewer",
    author: "urule",
    mountPoints: ["main-panel", "drawer"],
    entryType: "native",
    componentPath: "activity-logs",
    permissions: ["read:logs"],
    defaultConfig: {},
    icon: "data_exploration",
    category: "monitoring",
  },
  {
    id: "urule:integrations",
    name: "Integrations & MCP",
    version: "0.1.0",
    description: "Manage integrations and MCP tool connections",
    author: "urule",
    mountPoints: ["main-panel"],
    entryType: "native",
    componentPath: "integrations",
    permissions: ["read:integrations", "write:integrations"],
    defaultConfig: {},
    icon: "extension",
    category: "productivity",
  },
  {
    id: "urule:projects",
    name: "Projects & Kanban",
    version: "0.1.0",
    description: "Project management with kanban board",
    author: "urule",
    mountPoints: ["main-panel"],
    entryType: "native",
    componentPath: "projects",
    permissions: ["read:projects", "write:projects"],
    defaultConfig: {},
    icon: "work",
    category: "productivity",
  },
];
